version: "3.0"

services:
  testui:
    build:
      context: ./docker/test-ui
    image: cfwheels-testui:v1
    ports:
      - "3000:8080"

  lucee5:
    build:
      context: ./
      dockerfile: ./docker/lucee5/Dockerfile
    image: cfwheels-test-lucee5:v1
    volumes:
      # uncomment when developing with this docker-compose file
      # - ./:/cfwheels-test-suite
      - ./.CommandBox/artifacts:/root/.CommandBox/artifacts
    ports:
      - "60005:8080"

  lucee6:
    build:
      context: ./
      dockerfile: ./docker/lucee6/Dockerfile
    image: cfwheels-test-lucee6:v1
    volumes:
      # uncomment when developing with this docker-compose file
      # - ./:/cfwheels-test-suite
      - ./.CommandBox/artifacts:/root/.CommandBox/artifacts
    ports:
      - "60006:8080"

  adobe2016:
    build:
      context: ./
      dockerfile: ./docker/adobe2016/Dockerfile
    image: cfwheels-test-adobe2016:v1
    volumes:
      # uncomment when developing with this docker-compose file
      # - ./:/cfwheels-test-suite
      - ~/.CommandBox/artifacts:/root/.CommandBox/artifacts
    ports:
      - "62016:8080"

  adobe2018:
    build:
      context: ./
      dockerfile: ./docker/adobe2018/Dockerfile
    image: cfwheels-test-adobe2018:v1
    volumes:
      # uncomment when developing with this docker-compose file
      # - ./:/cfwheels-test-suite
      - ./.CommandBox/artifacts:/root/.CommandBox/artifacts
    ports:
      - "62018:8080"

  adobe2021:
    build:
      context: ./
      dockerfile: ./docker/adobe2021/Dockerfile
    image: cfwheels-test-adobe2021:v1
    volumes:
      # uncomment when developing with this docker-compose file
      # - ./:/cfwheels-test-suite
      - ./.CommandBox/artifacts:/root/.CommandBox/artifacts
    ports:
      - "62021:8080"

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wheelstestdb
      MYSQL_DATABASE: wheelstestdb
      MYSQL_USER: wheelstestdb
      MYSQL_PASSWORD: wheelstestdb

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: wheelstestdb
      POSTGRES_PASSWORD: wheelstestdb
      POSTGRES_INITDB_ARGS: --auth-host=md5

  sqlserver:
    build:
      context: ./
      dockerfile: ./docker/sqlserver/Dockerfile
    image: cfwheels-sqlserver:v1
    environment:
      MSSQL_SA_PASSWORD: x!bsT8t60yo0cTVTPq
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    # volumes:
      # - ./src/docker:/src/docker
